baseURL = "https://firej.org/"
languageCode = "ru-ru"
title = "firej.org"
theme = "m10c"

paginate = 10

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false
    guessSyntax = true

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[params]
  author = "Evgeny Bogdanov"
  description = "Блог о технологиях, умном доме и автоматизации"

[[params.social]]
  name = "github"
  url = "https://github.com/firej"
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/firejvlz"
[[params.social]]
  name = "instagram"
  url = "https://instagram.com/firejvlz"
[[params.social]]
  name = "telegram"
  url = "https://t.me/iamfirej"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
